root: true
env:
  es2021: true
  node: true
plugins:
  - prettier
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
  no-console: off
  no-continue: off
  import/extensions:
    - error
    - ignorePackages
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_' # <-- NOTE!
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      ignoreRestSiblings: true
